services:
    cba-php:
        build:
            context: .
            dockerfile: php.dockerfile
        networks:
            - cba-network
        volumes:
            - ./:/var/www/html
        user: "${WWWUSER}:${WWWGROUP}" # ID mặc định của linux
        restart: always
        depends_on:
            - mysql

    cba-nginx:
        image: nginx:latest
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - cba-network
        restart: always

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'cba-mysql:/var/lib/mysql'
        networks:
            - cba-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    cba-network:
        driver: bridge
volumes:
    cba-mysql:
        driver: local
